Join union members and users
profcomff/dwh-definitions pull request #113
Opened 2024-12-07 16:26 UTC by Wudext

2024-12-07 16:29 UTC, Zimovchik approved these changes

2024-12-07 16:35 UTC, parfenovma requested changes
а где миграция?

2024-12-07 18:32 UTC, parfenovma requested changes

2024-12-07 18:32 UTC, parfenovma commented on migrations/versions/20241207_2130_f31bd2cf406f_unionmemberjoin.py
> +    # ### commands auto generated by Alembic - please adjust! ###
вот эти комменты убери пож)

2024-12-07 18:32 UTC, parfenovma commented on migrations/versions/20241207_2130_f31bd2cf406f_unionmemberjoin.py
> +from alembic import op
тут щас линтер свалится

2024-12-11 07:56 UTC, Wudext commented on migrations/versions/20241207_2130_f31bd2cf406f_unionmemberjoin.py
> +from alembic import op
не свалился

2024-12-11 07:56 UTC, Wudext commented on migrations/versions/20241207_2130_f31bd2cf406f_unionmemberjoin.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Убрал

2024-12-11 07:58 UTC, parfenovma approved these changes

2024-12-11 08:00 UTC, merged