Add social class
profcomff/dwh-definitions pull request #14
Opened 2023-09-01 16:12 UTC by antimoda1

## Изменения
Добавлен класс Social Activity

## Детали реализации
Поля класса:
id: int, primary_key=True 
system: String
message: JSON
Все не могут быть нулями

## Check-List

- [+ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2023-09-01 16:20 UTC, dyakovri commented on profcomff_definitions/.project
Этот файл не должен попадать в git
Его нужно удалить отсюда и добавить в глобальный игнор. Как настроить глобальный игнор гита описано тут: https://stackoverflow.com/a/7335487

2023-09-01 16:20 UTC, dyakovri commented on migrations/versions/2cf9d03685ba_add_social.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Я обычно прошу убирать эти комментарии как знак того, что ты отчитал, что сгенерировалось автоматически и понял что все верно. Автоматика все-таки иногда подводит

2023-09-01 16:20 UTC, dyakovri commented on migrations/versions/2cf9d03685ba_add_social.py
> +    op.create_table_schema("TESTS_DATABASE")
Кажется, это схема для твоих тестов)

2023-09-01 16:20 UTC, dyakovri commented on migrations/versions/2cf9d03685ba_add_social.py
> +    op.create_table_schema("TESTS_DATABASE")
Наверное она нам не нужна в настоящей базе данных

2023-09-01 16:20 UTC, dyakovri commented on migrations/versions/2cf9d03685ba_add_social.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Их 4 – в начале и в конце обоих функций в этом файле

2023-09-01 16:20 UTC, dyakovri commented on profcomff_definitions/STG/social.py
> +	id: Mapped[int] = mapped_column(Integer, nullable=False, primary_key=True)
Давай тут уберем primary key. Эта таблица будет заполняться хрен знает как, primary_key создает дополнительные условия на то, что колонка должна быть заполнена, значения уникальные. При этом создает специальный каунтер "id следующего значения". Когда мы будет заполнять ее копированием из другой таблицы эти ограничения могут нам навредить.

2023-09-01 16:20 UTC, dyakovri commented on profcomff_definitions/STG/social.py
> +	id: Mapped[int] = mapped_column(Integer, nullable=False, primary_key=True)
Ну , собсна, поле изменений в этом файле надо будет сгенерировать новые миграции))

2023-09-01 19:22 UTC, dyakovri commented on .project
Файл project остался(

2023-09-01 19:22 UTC, dyakovri commented on migrations/versions/4df46ea2b0f9_add_social.py
> +    )
Странно, что тут осталась таблица test?

2023-09-01 19:22 UTC, dyakovri commented on migrations/versions/4df46ea2b0f9_add_social.py
> +    )
Ты их перегенерировал?

2023-09-01 19:22 UTC, dyakovri commented on profcomff_definitions/.project
Тоже файл project остался

2023-09-01 19:22 UTC, dyakovri commented on migrations/schema/__init__.py
@Wudext а норм, что у тебя тут все трется линтерами?

2023-09-01 19:24 UTC, dyakovri commented on migrations/versions/4df46ea2b0f9_add_social.py
> +    )
@Wudext кажется, тут проблема с тестовой схемой

2023-09-01 19:25 UTC, antimoda1 commented on .project
Я же его удалял. Странно, что вернулся

2023-09-01 19:29 UTC, antimoda1 commented on .project
![image](https://github.com/profcomff/dwh-definitions/assets/123952135/0b021348-b143-4747-ab6c-d1e640e0b039)
Проверил, вбив команду в терминал - до сих пор в исключениях стоит. Как он пророс?

2023-09-01 19:36 UTC, dyakovri commented on .project
Ты его добавл в исключения, а после этого из гита удалил?

2023-09-01 19:58 UTC, antimoda1 commented on .project
Поставил в исключения, но не удалил. Это да, косяк.
При попытке удалить, а потом навести миграцию (при включенном игноре) выдаёт ValueError: no dispatch function for object: <migrations.schema.operations.CreateTableSchemaOp object at 0x000001FD3B12A4D0> . Странно

2023-09-01 20:13 UTC, antimoda1 commented on .project
Не, дело в нём, даже если вернуть, всё равно миграции не генерируются.
Гипотеза,  в чём дело: в предыдущий раз после прохода blackом и isortом я не поменял миграции.  Кажется, правильный порядок такой:
сделать изменения в классе
накатить isort и ко в классе
сделать миграции
накатить isort и ко в миграциях 

а не
сделать изменения в классе
накатить миграции
накатить isort везде

2023-09-01 20:35 UTC, Wudext commented on migrations/versions/4df46ea2b0f9_add_social.py
> +    )
Да, видимо забыл снести когда коммитил управление правами

2023-09-01 20:36 UTC, Wudext commented on .project
Эта ошибка осталась? Если да то верни все импорты которые были, а то ты посносил импорты всех новых функций, я не уверен что без них будет работать

2023-09-01 20:38 UTC, Wudext commented on migrations/schema/__init__.py
Так и должно быть, весь новый функционал должен быть импортироваг

2023-09-01 20:40 UTC, Wudext requested changes
Повозвращай импорты логики алембика и снеси тестовую схему (test.py вроде файл)

2023-09-01 20:40 UTC, Wudext commented on migrations/schema/__init__.py
> -from .schemas import add_table_schema_to_model, compare_schemas
Импорты надо вернуть

2023-09-01 20:40 UTC, Wudext commented on migrations/rights/schemas.py
> -from .operations_groups import CreateGroupOp, DeleteGroupOp, GrantOnSchemaOp, RevokeOnSchemaOp
Этот тоже надо вернуть

2023-09-01 20:40 UTC, Wudext commented on migrations/rights/__init__.py
> -from .schemas import compare_groups
Импорты надо вернуть

2023-09-01 20:40 UTC, Wudext commented on migrations/env.py
> -from migrations import rights, schema
Этот импорт (8 строка) нужен

2023-09-02 14:31 UTC, Wudext commented on migrations/schema/__init__.py
> -from .schemas import add_table_schema_to_model, compare_schemas
Вернул

2023-09-02 14:32 UTC, Wudext commented on migrations/rights/schemas.py
> -from .operations_groups import CreateGroupOp, DeleteGroupOp, GrantOnSchemaOp, RevokeOnSchemaOp
Вернул

2023-09-03 10:35 UTC, Wudext commented on profcomff_definitions/.project
Убрал

2023-09-03 10:35 UTC, Wudext commented on migrations/versions/2cf9d03685ba_add_social.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Комментов нет

2023-09-03 10:35 UTC, Wudext commented on migrations/versions/2cf9d03685ba_add_social.py
> +    op.create_table_schema("TESTS_DATABASE")
Да, вроде ее снесли

2023-09-03 10:36 UTC, Wudext commented on profcomff_definitions/STG/social.py
> +	id: Mapped[int] = mapped_column(Integer, nullable=False, primary_key=True)
Без primary key и без ForeginKey на миграции будет выдаваться ошибка

2023-09-03 10:36 UTC, Wudext approved these changes

2023-09-03 10:36 UTC, Wudext commented on profcomff_definitions/.project
Убрал

2023-09-04 20:10 UTC, dyakovri commented
Докатится с #17

2023-09-04 20:10 UTC, closed without merging