добавление валидации
profcomff/dwh-definitions pull request #30
Opened 2024-04-21 10:49 UTC by SofyaFin

## Изменения
Добавлен файл validation.py

## Детали реализации
В validation.py описаны классы валидации и описаны схемы валидации

## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-04-27 07:44 UTC, Wudext requested changes
1) Всю валидацию закинуть в папку ODS/validation
2) dagtransport - нет расширения, должен быть в другом репозитории

2024-05-04 13:51 UTC, Wudext requested changes
Во всех классах валидации вместо нужных Field стоит mapped_column
В половине классов алхимии отсутствует mapped_column, используется какой-то неясный sa.Column
В некоторых строчках остуствуют тайпхинты.

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/Marketing.py
> +    id = Column(sa.Integer, primary_key=True)
Что за Column? Почему не mapped_column?

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/Pinger.py
> +    url =  sa.Column(URLType)
тут вообще перемешали Column и mapped_column

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/Pinger.py
> +    data = mapped_column(JSON)
Тайп хинта нет (: Mapped[int] - тайпхинт)

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/Print.py
> +    source: Mapped[str] = Column(String)
Опять Column

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Authv.py
> +    id: Mapped[int] = mapped_column(Integer, primary_key=True)
Здесь должны быть Field а не mapped_column

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Marketingv.py
> +    id = Column(sa.Integer, primary_key=True)
Column

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Marketingv.py
> +    email = sa.Column(EmailType)
Field

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Physicsv.py
> +    phone: Mapped[int] = mapped_column(Integer, nullable=True)
Field

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Pingerv.py
> +    url = sa.Column(URLType)
mapped_column

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Pingerv.py
> +    url = sa.Column(URLType)
И еще нет тайпхинта

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Pingerv.py
> +    data = mapped_column(JSON)
Нет тайпхинта

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Pingerv.py
> +    name: Mapped[str] = mapped_column("name", String)
Field

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Printv.py
> +    surname: Mapped[str] = mapped_column(String)
Field

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Printv.py
> +    option_copies: Mapped[int] = Column(Integer)
mapped_column

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Servicesv.py
> +    order: Mapped[int] = mapped_column(Integer)
field

2024-05-04 13:51 UTC, Wudext commented on profcomff_definitions/ODS/validation/Timetablev.py
> +    email = sa.Column(EmailType)
mapped_column, нет тайпхинта

2024-05-04 14:16 UTC, grigoriev-semyon commented on profcomff_definitions/ODS/Marketing.py
> +    id = Column(sa.Integer, primary_key=True)
Column это из SQLAlchemy 1.4
Мы ее выпилили год назад из прода
Во второй версии юзается mapped_column

2024-05-04 15:48 UTC, Wudext requested changes
У всех строчек в классах валидации после тайпхинта должна стоять = Field()
Чтобы nullable=True работал, нужно поменять тайпхинт (либо Optional[...] заблаговременно импортировав Optional из typing, либо ... | None)

2024-05-04 15:48 UTC, Wudext commented on profcomff_definitions/ODS/Physics.py
> +    email = sa.Column(EmailType)
Не поменяно на mapped_column

2024-05-04 15:48 UTC, Wudext commented on profcomff_definitions/ODS/validation/Authv.py
> +    id:int = Field(primary_key=True)
У Field нет параметра primary_key
Сделай просто Field()

2024-05-04 15:48 UTC, Wudext commented on profcomff_definitions/ODS/validation/Physicsv.py
> +    name: str = Field(nullable=True)
Для того, чтобы nullable=True работал нужно
1) Добавить from typing import Optional
2) Вместо тайпхинта name: str прописать name: Optional[str]

Или можно поменять тайпхинт на name: str | None

2024-05-04 15:48 UTC, Wudext commented on profcomff_definitions/ODS/Socialv.py
> +class WebhookStorageSoc(BaseModel):
Если это класс валидации - файл с ним должен лежать в папке validation (а он просто в ODS)

2024-05-04 15:48 UTC, Wudext commented on profcomff_definitions/ODS/validation/Printv.py
> +    pin: str
pin: str = Field()

2024-05-04 23:14 UTC, grigoriev-semyon commented on profcomff_definitions/ODS/validation/Printv.py
> +    pin: str
это не обязательно

2024-05-04 23:15 UTC, grigoriev-semyon commented
```python
class X(pydantic.BaseModel):
    y: int
```
валидная запись
не надо писать пустой Field

2024-05-06 14:37 UTC, Wudext commented on profcomff_definitions/ODS/validation/Authv.py
> +    id:int = Field(primary_key=True)
Или просто id: int

2024-05-07 06:15 UTC, dyakovri requested changes

2024-05-07 06:15 UTC, dyakovri commented on profcomff_definitions/ODS/Auth.py
> +    update_ts: Mapped[datetime.datetime] = mapped_column(DateTime)
У всех таблиц в ODS и выше нужны комментарии на таблицу и на колонки

Пример: https://github.com/profcomff/dwh-definitions/blob/main/profcomff_definitions/ODS/infra_logs.py#L9-L15

2024-05-07 06:15 UTC, dyakovri commented on profcomff_definitions/ODS/Auth.py
> +    is_deleted: Mapped[bool] = mapped_column(Boolean)
Нет смысла писать `= mapped_column(...)`, если там только тип данных

Тип данных возьмется из `Mapped[bool]`

Примеры:
- Для STG можно так: https://github.com/profcomff/dwh-definitions/blob/main/profcomff_definitions/STG/infra.py#L11-L12
- Если столбику нужны комментарии, то можно так: https://github.com/profcomff/dwh-definitions/blob/main/profcomff_definitions/ODS/infra_logs.py#L9-L15

2024-05-07 06:15 UTC, dyakovri commented on profcomff_definitions/ODS/Auth.py
> +    parent_id: Mapped[int] = mapped_column(Integer)
Этот столбец может содержать значения Null

2024-05-07 06:15 UTC, dyakovri commented on profcomff_definitions/ODS/Auth.py
Файлы именуются маленькими буквами

2024-05-07 06:15 UTC, dyakovri commented on profcomff_definitions/ODS/validation/Authv.py
> +from pydantic import int, str, Field, EmailStr
Кому и зачем они нужны, как они будут использоваться? @Wudext

2024-05-07 08:02 UTC, Wudext commented on profcomff_definitions/ODS/validation/Authv.py
> +from pydantic import int, str, Field, EmailStr
Обсудили в тг

2024-05-07 16:19 UTC, dyakovri commented on profcomff_definitions/ODS/validation/Authv.py
> +from pydantic import int, str, Field, EmailStr
Как это использовать я все равно не понял 
Можно пример?

2024-10-24 17:17 UTC, closed without merging