#44
profcomff/dwh-definitions pull request #53
Opened 2024-06-24 09:53 UTC by SofyaFin

## Изменения
44 на нужной ветке
## Детали реализации

## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-06-24 10:11 UTC, dyakovri commented on migrations/versions/20240531_2333_b003a52d0992_dm_logs.py
> +        'incident',
`incident_hist`, наверное
Лучше у @mixx3 уточнить

2024-06-24 10:24 UTC, mixx3 approved these changes

2024-06-24 10:24 UTC, mixx3 commented on profcomff_definitions/DM/infra_logs.py
> +    create_ts: Mapped[datetime] = mapped_column(comment="Время, когда произошла ошибка")
добавь пожалуйста поле нарезки лога, назови его как-нибудь msk_record_loaded_dttm или как-то так
потом это сильно упростит дебаг и код в эирфлоу таске)

2024-06-24 16:02 UTC, mixx3 commented on migrations/versions/20240510_1330_8b6f4a99f692_add_dimroomact_to_dm.py
> +import sqlalchemy as sa
а почему тут есть изменения?)

2024-06-24 16:11 UTC, SofyaFin commented on migrations/versions/20240510_1330_8b6f4a99f692_add_dimroomact_to_dm.py
> +import sqlalchemy as sa
линтинг

2024-06-24 20:26 UTC, SofyaFin commented on migrations/versions/20240531_2333_b003a52d0992_dm_logs.py
> +        'incident',
пофикшено

2024-06-25 03:09 UTC, grigoriev-semyon requested changes

2024-06-25 03:09 UTC, grigoriev-semyon commented on profcomff_definitions/DM/infra_logs.py
> +class Incident_hint(Base):
Название должно быть в CamelCase

2024-06-25 03:09 UTC, grigoriev-semyon commented on profcomff_definitions/DM/infra_logs.py
> +    create_ts: Mapped[datetime] = mapped_column(comment="Время, когда произошла ошибка")
не пофикшено

2024-06-25 03:09 UTC, grigoriev-semyon commented on profcomff_definitions/DM/infra_logs.py
> +    msk_record_loaded_dttm: Mapped[str] = mapped_column(comment="Поле нарезки лога")
зачем это тут?

2024-06-25 03:10 UTC, grigoriev-semyon commented on profcomff_definitions/DM/infra_logs.py
> +    msk_record_loaded_dttm: Mapped[str] = mapped_column(comment="Поле нарезки лога")
Миша говорил добавить это в таблице новой

2024-06-25 09:40 UTC, SofyaFin commented on profcomff_definitions/DM/infra_logs.py
> +class Incident_hint(Base):
исправила

2024-06-25 09:41 UTC, SofyaFin commented on profcomff_definitions/DM/infra_logs.py
> +    msk_record_loaded_dttm: Mapped[str] = mapped_column(comment="Поле нарезки лога")
поменяно

2024-06-25 09:41 UTC, SofyaFin commented on profcomff_definitions/DM/infra_logs.py
> +    create_ts: Mapped[datetime] = mapped_column(comment="Время, когда произошла ошибка")
теперь пофикшено

2024-06-25 09:53 UTC, mixx3 commented on migrations/versions/20240625_1206_5714921e11a0_incident_logs.py
> +        'incident_hint',
typo

2024-06-25 09:55 UTC, mixx3 reviewed
пару моментов исправить и можно мержить))

2024-06-25 09:55 UTC, mixx3 commented on profcomff_definitions/DM/infra_logs.py
> +class IncidentHint(Base):
typo

2024-06-25 09:55 UTC, mixx3 commented on profcomff_definitions/DM/infra_logs.py
> +    msk_record_loaded_dttm: Mapped[str] = mapped_column(comment="Поле нарезки лога")
супер название, ставлю лайк!
лучше его datetime сделать конечно)

2024-06-25 10:05 UTC, SofyaFin commented on profcomff_definitions/DM/infra_logs.py
> +    msk_record_loaded_dttm: Mapped[str] = mapped_column(comment="Поле нарезки лога")
уже datetime)

2024-06-25 10:05 UTC, SofyaFin commented on profcomff_definitions/DM/infra_logs.py
> +class IncidentHint(Base):
yoooo fixed

2024-06-25 11:02 UTC, Wudext approved these changes

2024-06-25 11:03 UTC, grigoriev-semyon approved these changes

2024-06-25 11:03 UTC, merged