class(table) info added + migration
profcomff/dwh-definitions pull request #59
Opened 2024-07-23 16:03 UTC by RedstoneEnjoyer

## Изменения

## Детали реализации

## Check-List

2024-07-23 17:00 UTC, Wudext requested changes
Удалить папку .idea целиком
Проверить, что за удаление колонок в конце миграции (в upgrade)

2024-07-25 11:59 UTC, mixx3 requested changes

2024-07-25 11:59 UTC, mixx3 commented on migrations/versions/20240723_1829_0801e032e4e7_my_migration.py
> +import os
import os перемести на первое место среди импортов, можно посмотреть как сделано в других миграциях
например, https://github.com/profcomff/dwh-definitions/blob/main/migrations/versions/20240505_0010_a80b250420e4_schema_integrity_fixes.py#L9

2024-07-25 11:59 UTC, mixx3 commented on migrations/versions/20240723_1829_0801e032e4e7_my_migration.py
> +    # ### commands auto generated by Alembic - please adjust! ###
также все вот такие комменты про auto gen обычно убирают
делается это для того, чтобы все точно знали, что человек эту миграцию глазами проверил и всё было ок)

2024-07-25 11:59 UTC, mixx3 commented on profcomff_definitions/ODS/info.py
> +    work_location: Mapped[str | None] = mapped_column(String, nullable=True)
в конце файла добавь строку

2024-07-25 11:59 UTC, mixx3 commented on profcomff_definitions/ODS/info.py
> +from sqlalchemy import String
импорты нужно привести в порядок чтобы линтер не ругался
скорее всего он ругается что не в алфавитном порядке стоят
подробнее можно почитать вот здесь https://peps.python.org/pep-0008/#imports

2024-07-25 11:59 UTC, mixx3 commented on profcomff_definitions/ODS/info.py
> +class info(Base):
класс всегда с большой буквы называют

2024-07-25 11:59 UTC, mixx3 commented on profcomff_definitions/ODS/info.py
> +    user_id: Mapped[int] = mapped_column(String, index=True, primary_key=True)
так это int или String ?)

2024-07-26 19:20 UTC, Wudext approved these changes
Звучит хайпово, работоспособность миграции под ответственность @mixx3

2024-07-27 11:20 UTC, mixx3 requested changes

2024-07-27 11:20 UTC, mixx3 commented on migrations/versions/20240723_1829_0801e032e4e7_my_migration.py
> +"""my migration
Лучше написать что-то в духе add_ods_user_info вместо my_migration

2024-07-31 15:02 UTC, mixx3 approved these changes

2024-07-31 15:03 UTC, mixx3 requested changes
ещё линтеры падают
(

2024-07-31 15:28 UTC, mixx3 approved these changes

2024-07-31 15:30 UTC, mixx3 commented on migrations/versions/20240723_1829_0801e032e4e7_my_migration.py
> +"""my migration
я заресолвил

2024-07-31 15:31 UTC, merged